Fix compilation when building with clang
Clang is stricter when reporting errors. In this case, when building
with CONFIG_FB unset, compiling with clang will produce the following
error:
evdi_fb.c:88:12: error: unused function 'evdi_handle_damage' [-Werror,-Wunused-function]
static int evdi_handle_damage(struct evdi_framebuffer *fb,
           ^
1 error generated.

Since evdi_handle_damage() is only used when CONFIG_FB is set, move the
`ifdef CONFIG_FB` to encapsulate the evdi_handle_damage() function.

Tested with copy of evdi imported into the chromeos-5.10 kernel.